{
 "title": "Grafana metrics",
 "description": "Metrics about Grafana",
 "tags": [
  "grafana",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "行标题", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "任务完成平均耗时",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(thread_pool_execute_time_seconds_sum[$__range]) / rate(thread_pool_execute_time_seconds_count[$__range])"
    }
   ]
  },
  {
   "title": "线程池完成任务总数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "thread_pool_completed_task_count_total"
    },
    {}
   ]
  },
  {
   "title": "任务等待平均时长",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(thread_pool_wait_time_seconds_sum[$__range]) / rate(thread_pool_wait_time_seconds_count[$__range])",
     "legendFormat": "{{status_code}}",
     "target": "dev.grafana.cb-office.alerting.active_alerts"
    }
   ]
  },
  {
   "title": "队列占比",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "thread_pool_queue_size \r\n/ \r\nthread_pool_queue_capacity\r\n* 100"
    }
   ]
  },
  {
   "title": "活跃线程占比",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thread_pool_active_count\r\n/ \r\nthread_pool_max_pool_size\r\n* 100",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "拒绝任务变化值",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(thread_pool_reject_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}