
smart-pool:
  enabled: true

spring:
  application:
    name: smart-pool-admin-server
  config:
    import: optional:nacos:thread-pool-config.yaml?group=DEFAULT_GROUP&refreshEnabled=true&encoding=UTF-8
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/smart_pool?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        enabled: true
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        data-id: smart-pool.yaml
        group: DEFAULT_GROUP
        file-extension: yaml
        enable-remote-sync-config: false

  mail:
    host: smtp.qq.com
    port: 587
    username: 2241674068@qq.com
    password: bltfttpzahzlebcf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  output:
    ansi:
      enabled: always

    
    # 支付处理线程池
#    payment-pool:
#      rules:
#        - type: CAPACITY
#          threshold: 85
#          count: 3
#          period: 60
#          silencePeriod: 180
#          enabled: true
#        - type: LIVENESS
#          threshold: 80
#          count: 2
#          period: 60
#          silencePeriod: 180
#          enabled: true
#        - type: RUN_TIMEOUT
#          threshold: 8
#          count: 1
#          silencePeriod: 180
#          enabled: true
#        - type: REJECT
#          period: 60
#          silencePeriod: 300
#          enabled: true
#      monitor-interval: 5000

server:
  port: 8081
  servlet:
    context-path: /admin

logging:
  level:
    com.xiao.smartpooladminserver: INFO

# Actuator监控配置（核心：暴露Prometheus端点）
management:
  # 端点通用配置
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics # 暴露prometheus端点
      base-path: /actuator # 端点基础路径（默认/actuator）
    enabled-by-default: true # 默认开启所有端点
  # 单个端点配置
  endpoint:
    prometheus:
      enabled: true # 开启Prometheus端点
    health:
      show-details: always # 健康检查显示详细信息
  metrics:
    tags:
      application: ${spring.application.name}
      env: dev
    naming:
      convention: prometheus

  prometheus:
    metrics:
      export:
        step: 1m

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiao.smartpoolcore.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


