
server:
  port: 8081
  servlet:
    context-path: /admin

smart-pool:
  enabled: true

spring:
  application:
    name: smart-pool-admin-server
  output:
    ansi:
      enabled: always
  config:
    import: optional:nacos:thread-pool-config.yaml?group=DEFAULT_GROUP&refreshEnabled=true&encoding=UTF-8

  data:
    redis:
      password: 123456
      host: localhost
      port: 6379
      database: 7
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/smart_pool?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        enabled: true
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        data-id: smart-pool.yaml
        group: DEFAULT_GROUP
        file-extension: yaml
        enable-remote-sync-config: false

  mail:
    host: smtp.qq.com
    port: 587
    username: 2241674068@qq.com
    password: bltfttpzahzlebcf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


rocketmq:
  # NameServer 地址
  name-server: 127.0.0.1:9876

  producer:
    group: reject-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
    max-message-size: 4194304    # 最大消息体大小(byte)，默认4MB
  consumer:
    group: reject-consumer-group
    consume-thread-min: 20       # 最小消费线程数，默认20
    consume-thread-max: 64       # 最大消费线程数，默认64
    consume-mode: CLUSTERING     # 消费模式：CLUSTERING(集群) / BROADCASTING(广播)


logging:
  level:
    com.xiao.smartpooladminserver: INFO

# Actuator监控配置（暴露Prometheus端点）
management:
  # 端点通用配置
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics # 暴露prometheus端点
      base-path: /actuator                      # 端点基础路径（默认/actuator）
    enabled-by-default: true                    # 默认开启所有端点
  # 单个端点配置
  endpoint:
    prometheus:
      enabled: true # 开启Prometheus端点
    health:
      show-details: always # 健康检查显示详细信息
  metrics:
    tags:
      application: ${spring.application.name}
      env: dev
    naming:
      convention: prometheus

  prometheus:
    metrics:
      export:
        step: 1m

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiao.smartpoolcore.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


